### ISSUE TITLE
Create a birdhouse WPS for midas-subsetting: goldfinch

### ISSUE THREAD

**Issue by agstephens** [cedadev/ceda-wps-migration#12]
Create a birdhouse WPS for midas-subsetting:

Use cookie-cutter: 

https://github.com/bird-house/cookiecutter-birdhouse

Call the new WPS: "goldfinch"

Put it under `cedadev`.

**Comment by agstephens** [comment]
Hi @ellesmith88, I am going cross-project here. I thought it might be useful. 
For the CEDA-WPS replacement, we are going to create 3 new WPSs based on Birdhouse. This issue represents the first: "goldfinch".

Please can you try using Carsten's cookie-cutter for birdhouse to create this WPS and then put the contents into: https://github.com/cedadev/goldfinch/ - which I have created and given you full access to.

**Comment by agstephens** [comment]
Hi @ellesmith88, I think you said you were setting this one up. Is it ready? Thanks

**Comment by ellesmith88** [comment]
@agstephens Yes it's at https://github.com/cedadev/goldfinch/.
I didn't get round to trying the fix the travis tests though, I haven't changed anything after using the cookie-cutter so not sure why there's a problem there.

**Comment by agstephens** [comment]
Thanks @ellesmith88 , leave the travis tests to us.
